<a href="https://colab.research.google.com/github/poojitha-sys281/Banking_system/blob/main/Project1_SQL_query_IMDB_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rounakbanik/the-movies-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/rounakbanik/the-movies-dataset?dataset_version_number=7...

100%|██████████| 228M/228M [00:08<00:00, 28.9MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/rounakbanik/the-movies-dataset/versions/7

# Importing the libaries

In [ ]:
import numpy as np# mathematical operations
import pandas as pd# data manipulation tool
import matplotlib as plt# data visualization tool
import seaborn as sns# data visualization tool
import sqlite3# serverless database

#Hints and tips
1. connect your database (or create a connection) -> sqlite3.connect(database)

2. use the curser function -> database variable.cursor ()

# Workflow
1. You need to establish a connection to the SQLite database by creating a connecting object
2. we have to create cursor object using the cursor() method

3. now we are ready to execute the query-> cursor_object.execute('query')
4. To fetch the data,then use fetchchall() method of the cursor

# Establishing the connection with the database

In [ ]:
data= pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv')

In [ ]:
conn=sqlite3.connect('database1.sqlite')
cur=conn.cursor()

In [ ]:
data= pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv')

In [ ]:
conn=sqlite3.connect('database1.sqlite')
cur=conn.cursor()

#THE REAL PROJECT

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!wget https://raw.githubusercontent.com/peetck/IMDB-Top1000-Movies/master/IMDB-Movie-Data.csv \
    -O /content/drive/MyDrive/imdb_top_1000.csv

--2025-08-12 12:23:32--  https://raw.githubusercontent.com/peetck/IMDB-Top1000-Movies/master/IMDB-Movie-Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 309028 (302K) [text/plain]
Saving to: ‘/content/drive/MyDrive/imdb_top_1000.csv’

/content/drive/MyDr 100%[===================>] 301.79K  --.-KB/s    in 0.04s

2025-08-12 12:23:33 (6.79 MB/s) - ‘/content/drive/MyDrive/imdb_top_1000.csv’ saved [309028/309028]

In [3]:
import numpy as np# mathematical operations
import pandas as pd# data manipulation tool
import matplotlib as plt# data visualization tool
import seaborn as sns# data visualization tool
import sqlite3# serverless database

In [4]:
conn=sqlite3.connect('database1.sqlite')
cur=conn.cursor()

In [5]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/imdb_top_1000.csv')
print(df.head())

   Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13         76
1     7.0  485820              126.46         65
2     7.3  157606              138.12         62
3     7.2   60545              270.32         59
4     6.2  393727              325.02         40

In [6]:
df.to_sql('new_data', conn, if_exists='replace', index=False)

1000

In [7]:
cur.execute('SELECT * FROM new_data')

In [8]:
table=cur.fetchall()

In [9]:
df=pd.DataFrame(table,columns=[
    'S.No',
    'Title',
    'Genre',
    'Description',
    'Director',
    'Actors',
    'Year',
    'Runtime (Minutes)',
    'IMDB Rating',
    'Votes',
    'Revenue (Millions)',
    'Metascore'
]
)

In [ ]:
df

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,0.00,45
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,0.00,22
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11

In [ ]:
cur.execute('select "Title" from new_data')

In [ ]:
data1=cur.fetchall()

In [ ]:
df1=pd.DataFrame(data1,columns=['Title'])

In [ ]:
df1

                       Title
0    Guardians of the Galaxy
1                 Prometheus
2                      Split
3                       Sing
4              Suicide Squad
..                       ...
995     Secret in Their Eyes
996          Hostel: Part II
997   Step Up 2: The Streets
998             Search Party
999               Nine Lives

[1000 rows x 1 columns]

In [ ]:
number=len(df1)
print('These many movies are present in the table:',number)

These many movies are present in the table: 1000

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [ ]:
cur.execute('select count(Title) from new_data')

In [ ]:
count=cur.fetchall()

In [ ]:
print(count[0])

(1000,)

In [ ]:
cur.execute("select * from new_data where Director in ('David Ayer','Justin Lin')")

In [ ]:
dic=cur.fetchall()

In [24]:
df=pd.DataFrame(table,columns=[
    'S.No',
    'Title',
    'Genre',
    'Description',
    'Director',
    'Actors',
    'Year',
    'Runtime (Minutes)',
    'IMDB Rating',
    'Votes',
    'Revenue (Millions)',
    'Metascore'
]
)

In [25]:
df

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,0.00,45
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,0.00,22
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11

# Print the director names that starts with 'Justin'

In [ ]:
cur.execute("select * from new_data where Director LIKE 'Justin%'")

In [ ]:
directors=cur.fetchall()
df=pd.DataFrame(directors)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36
1,49,Star Trek Beyond,"Action,Adventure,Sci-Fi",The USS Enterprise crew explores the furthest ...,Justin Lin,"Chris Pine, Zachary Quinto, Karl Urban, Zoe Sa...",2016,122,7.1,164567,158.80,68
2,135,Furious 6,"Action,Crime,Thriller",Hobbs has Dominic and Brian reassemble their c...,Justin Lin,"Vin Diesel, Paul Walker, Dwayne Johnson, Miche...",2013,130,7.1,318051,238.67,61
3,263,Dear White People,"Comedy,Drama",The lives of four black students at an Ivy Lea...,Justin Simien,"Tyler James Williams, Tessa Thompson, Kyle Gal...",2014,108,6.2,21715,4.40,79
4,309,The Fast and the Furious: Tokyo Drift,"Action,Crime,Thriller",A teenager becomes a major competitor in the w...,Justin Lin,"Lucas Black, Zachery Ty Bryan, Shad Moss, Dami...",2006,104,6.0,193479,62.49,45
5,320,Fast Five,"Action,Crime,Thriller",Dominic Toretto and his crew of street racers ...,Justin Lin,"Vin Diesel, Paul Walker, Dwayne Johnson, Jorda...",2011,131,7.3,300803,209.81,66
6,341,Fast & Furious,"Action,Crime,Thriller","Brian O'Conner, back working for the FBI in Lo...",Justin Lin,"Vin Diesel, Paul Walker, Michelle Rodriguez, J...",2009,107,6.6,217464,155.02,46
7,480,Macbeth,"Drama,War","Macbeth, the Thane of Glamis, receives a proph...",Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jack Mad...",2015,113,6.7,41642,0.00,71
8,948,King Cobra,"Crime,Drama",This ripped-from-the-headlines drama covers th...,Justin Kelly,"Garrett Clayton, Christian Slater, Molly Ringw...",2016,91,5.6,3990,0.03,48
9,950,Kicks,Adventure,Brandon is a 15 year old whose dream is a pair...,Justin Tipping,"Jahking Guillory, Christopher Jordan Wallace,C...",2016,80,6.1,2417,0.15,69
10,963,The Other Boleyn Girl,"Biography,Drama,History",Two sisters contend for the affection of King ...,Justin Chadwick,"Natalie Portman, Scarlett Johansson, Eric Bana...",2008,115,6.7,88260,26.81,50

In [ ]:
print(directors)

[(30, "Assassin's Creed", 'Action,Adventure,Drama', 'When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.', 'Justin Kurzel', 'Michael Fassbender, Marion Cotillard, Jeremy Irons,Brendan Gleeson', 2016, 115, 5.9, 112813, 54.65, 36), (49, 'Star Trek Beyond', 'Action,Adventure,Sci-Fi', 'The USS Enterprise crew explores the furthest reaches of uncharted space, where they encounter a new ruthless enemy who puts them and everything the Federation stands for to the test.', 'Justin Lin', 'Chris Pine, Zachary Quinto, Karl Urban, Zoe Saldana', 2016, 122, 7.1, 164567, 158.8, 68), (135, 'Furious 6', 'Action,Crime,Thriller', 'Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.', 'Justin Lin', 'Vin Diesel, Paul Walker, Dwayne Johnson, Michelle Rodriguez', 2013, 130, 7.1, 318051, 238.67, 61), (263, 'Dear White People', 'Comedy,Drama', 'The lives of four black students at an Ivy League college.', 'Justin Simien', 'Tyler James Williams, Tessa Thompson, Kyle Gallner,Teyonah Parris', 2014, 108, 6.2, 21715, 4.4, 79), (309, 'The Fast and the Furious: Tokyo Drift', 'Action,Crime,Thriller', 'A teenager becomes a major competitor in the world of drift racing after moving in with his father in Tokyo to avoid a jail sentence in America.', 'Justin Lin', 'Lucas Black, Zachery Ty Bryan, Shad Moss, Damien Marzette', 2006, 104, 6.0, 193479, 62.49, 45), (320, 'Fast Five', 'Action,Crime,Thriller', 'Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.', 'Justin Lin', 'Vin Diesel, Paul Walker, Dwayne Johnson, Jordana Brewster', 2011, 131, 7.3, 300803, 209.81, 66), (341, 'Fast & Furious', 'Action,Crime,Thriller', "Brian O'Conner, back working for the FBI in Los Angeles, teams up with Dominic Toretto to bring down a heroin importer by infiltrating his operation.", 'Justin Lin', 'Vin Diesel, Paul Walker, Michelle Rodriguez, Jordana Brewster', 2009, 107, 6.6, 217464, 155.02, 46), (480, 'Macbeth', 'Drama,War', 'Macbeth, the Thane of Glamis, receives a prophecy from a trio of witches that one day he will become King of Scotland. Consumed by ambition and spurred to action by his wife, Macbeth murders his king and takes the throne for himself.', 'Justin Kurzel', 'Michael Fassbender, Marion Cotillard, Jack Madigan,Frank Madigan', 2015, 113, 6.7, 41642, 0.0, 71), (948, 'King Cobra', 'Crime,Drama', 'This ripped-from-the-headlines drama covers the early rise of gay porn headliner Sean Paul Lockhart a.k.a. Brent Corrigan, before his falling out with the producer who made him famous. When... See full summary »', 'Justin Kelly', 'Garrett Clayton, Christian Slater, Molly Ringwald,James Kelley', 2016, 91, 5.6, 3990, 0.03, 48), (950, 'Kicks', 'Adventure', "Brandon is a 15 year old whose dream is a pair of fresh Air Jordans. Soon after he gets his hands on them, they're stolen by a local hood, causing Brandon and his two friends to go on a dangerous mission through Oakland to retrieve them.", 'Justin Tipping', 'Jahking Guillory, Christopher Jordan Wallace,Christopher Meyer, Kofi Siriboe', 2016, 80, 6.1, 2417, 0.15, 69), (963, 'The Other Boleyn Girl', 'Biography,Drama,History', 'Two sisters contend for the affection of King Henry VIII.', 'Justin Chadwick', 'Natalie Portman, Scarlett Johansson, Eric Bana,Jim Sturgess', 2008, 115, 6.7, 88260, 26.81, 50)]

# Print 3 most popular movies

In [ ]:
cur.execute("SELECT Title FROM new_data ORDER BY 'IMDB Rating' desc LIMIT 3 ")

In [ ]:
movies

NameError: name 'movies' is not defined

In [ ]:
movies=cur.fetchall()
print(f'The movies are {movies[0][0]},{movies[1][0]} and {movies[2][0]}')

The movies are Guardians of the Galaxy,Prometheus and Split

In [ ]:
df11=pd.DataFrame(movies)

In [ ]:
df11

                         0
0  Guardians of the Galaxy
1               Prometheus
2                    Split

#Print three most bankable movies

In [27]:
cur.execute('SELECT Title, "Revenue (Millions)"	FROM new_data ORDER BY "Revenue (Millions)" desc LIMIT 3')

In [28]:
movie=cur.fetchall()

In [29]:
movie

[('Star Wars: Episode VII - The Force Awakens', 936.63),
 ('Avatar', 760.51),
 ('Jurassic World', 652.18)]

In [30]:
print(f'The movies are\n {movie[0][0]},\n{movie[1][0]} \t and\n {movie[2][0]} \n and their budget is {movie[0][1]},{movie[1][1]} and {movie[2][1]}')

The movies are
 Star Wars: Episode VII - The Force Awakens,
Avatar 	 and
 Jurassic World
 and their budget is 936.63,760.51 and 652.18

In [31]:
df

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,0.00,45
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,0.00,22
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11

#print the movie title where that got high imdb rating and released since 2014

In [32]:
cur.execute('select Title from new_data where Year>2014  ORDER BY "IMDB Rating"  desc LIMIT 1 ')

In [33]:
awarded=cur.fetchall()
awarded

[('Split',)]

In [34]:
print(f'The movie with the highest imdb rating is {awarded[0][0]}')

The movie with the highest imdb rating is Split

#print the name of the director who have made highest movies of all directors

In [35]:
cur.execute('SELECT director FROM new_data GROUP BY director ORDER BY COUNT(*) DESC LIMIT 1')

In [36]:
curren=cur.fetchall()

In [37]:
print(curren)

[('Ridley Scott',)]

In [38]:
cur.execute("select Title from new_data where Director LIKE 'Ridley Scott'")

In [39]:
res=cur.fetchall()

In [40]:
res

[('Prometheus',),
 ('The Martian',),
 ('Robin Hood',),
 ('American Gangster',),
 ('Exodus: Gods and Kings',),
 ('The Counselor',),
 ('A Good Year',),
 ('Body of Lies',)]

#print the bankable director name

In [46]:
cur.execute('''
    SELECT "Director", SUM("Revenue (Millions)") AS total_revenue
    FROM new_data
    GROUP BY "Director"
    ORDER BY total_revenue DESC
    LIMIT 1
''')

In [47]:
cur.fetchall()

[('J.J. Abrams', 1683.4499999999998)]

In [18]:
cur.execute('SELECT Title FROM new_data ORDER BY "Revenue (Millions)" DESC LIMIT 10')

In [19]:
moviesare=cur.fetchall()

In [20]:
moviesare

[('Star Wars: Episode VII - The Force Awakens',),
 ('Avatar',),
 ('Jurassic World',),
 ('The Avengers',),
 ('The Dark Knight',),
 ('Rogue One',),
 ('Finding Dory',),
 ('Avengers: Age of Ultron',),
 ('The Dark Knight Rises',),
 ('The Hunger Games: Catching Fire',)]

In [ ]:
df1=pd.DataFrame(moviesare)

In [ ]:
df1

                                            0
0  Star Wars: Episode VII - The Force Awakens
1                                      Avatar
2                              Jurassic World
3                                The Avengers
4                             The Dark Knight
5                                   Rogue One
6                                Finding Dory
7                     Avengers: Age of Ultron
8                       The Dark Knight Rises
9             The Hunger Games: Catching Fire

#Revenue Analysis :--> tell the top 10 highest Revenue making movies

In [52]:
cur.execute("SELECT * FROM new_data ORDER BY 'Revenue (Millions)' DESC LIMIT 10")

In [53]:
df2=pd.DataFrame(cur.fetchall(),columns=[
    'S.No',
    'Title',
    'Genre',
    'Description',
    'Director',
    'Actors',
    'Year',
    'Runtime (Minutes)',
    'IMDB Rating',
    'Votes',
    'Revenue (Millions)',
    'Metascore'
])

In [54]:
df2

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,0.00,71
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41

# MetaScore Analysis :-->Top10 movies with highest metascore

In [55]:
cur.execute('SELECT * FROM new_data ORDER BY "Metascore" DESC LIMIT 10')

In [56]:
df3=pd.DataFrame(cur.fetchall(),columns=[
    'S.No',
    'Title',
    'Genre',
    'Description',
    'Director',
    'Actors',
    'Year',
    'Runtime (Minutes)',
    'IMDB Rating',
    'Votes',
    'Revenue (Millions)',
    'Metascore'
])

In [57]:
df3

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,657,Boyhood,Drama,"The life of Mason, from early childhood to his...",Richard Linklater,"Ellar Coltrane, Patricia Arquette, Ethan Hawke...",2014,165,7.9,286722,25.36,100
1,42,Moonlight,Drama,"A chronicle of the childhood, adolescence and ...",Barry Jenkins,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",2016,111,7.5,135095,27.85,99
2,231,Pan's Labyrinth,"Drama,Fantasy,War","In the falangist Spain of 1944, the bookish yo...",Guillermo del Toro,"Ivana Baquero, Ariadna Gil, Sergi López,Maribe...",2006,118,8.2,498879,37.62,98
3,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96
4,112,12 Years a Slave,"Biography,Drama,History","In the antebellum United States, Solomon North...",Steve McQueen,"Chiwetel Ejiofor, Michael Kenneth Williams, Mi...",2013,134,8.1,486338,56.67,96
5,490,Ratatouille,"Animation,Comedy,Family",A rat who can cook makes an unusual alliance w...,Brad Bird,"Brad Garrett, Lou Romano, Patton Oswalt,Ian Holm",2007,111,8.0,504039,206.44,96
6,510,Gravity,"Drama,Sci-Fi,Thriller",Two astronauts work together to survive after ...,Alfonso Cuarón,"Sandra Bullock, George Clooney, Ed Harris, Ort...",2013,91,7.8,622089,274.08,96
7,325,The Social Network,"Biography,Drama",Harvard student Mark Zuckerberg creates the so...,David Fincher,"Jesse Eisenberg, Andrew Garfield, Justin Timbe...",2010,120,7.7,510100,96.92,95
8,407,Zero Dark Thirty,"Drama,History,Thriller",A chronicle of the decade-long hunt for al-Qae...,Kathryn Bigelow,"Jessica Chastain, Joel Edgerton, Chris Pratt, ...",2012,157,7.4,226661,95.72,95
9,502,Carol,"Drama,Romance",An aspiring photographer develops an intimate ...,Todd Haynes,"Cate Blanchett, Rooney Mara, Sarah Paulson, Ky...",2015,118,7.2,77995,0.25,95

#Print the Details of the movies where the movies with most votes should be at the top

In [58]:
cur.execute('SELECT * FROM new_data ORDER BY votes DESC LIMIT 10')

In [59]:
df4=pd.DataFrame(cur.fetchall(),columns=[
    'S.No',
    'Title',
    'Genre',
    'Description',
    'Director',
    'Actors',
    'Year',
    'Runtime (Minutes)',
    'IMDB Rating',
    'Votes',
    'Revenue (Millions)',
    'Metascore'
])

In [127]:
df4.columns

Index(['S.No', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'IMDB Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [60]:
df4

,S.No,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),IMDB Rating,Votes,Revenue (Millions),Metascore
0,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82
1,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74
2,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78
3,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74
4,77,The Avengers,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69
5,145,Django Unchained,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81
6,78,Inglourious Basterds,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69
7,100,The Departed,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85
8,88,Avatar,"Action,Adventure,Fantasy",A paraplegic marine dispatched to the moon Pan...,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",2009,162,7.8,935408,760.51,83
9,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66

#Print the Director name ,number of movies,total revenue

In [90]:
cur.execute('''SELECT "Director",COUNT(*) AS movie_count,SUM("Revenue (Millions)")as total_revenue FROM new_data GROUP BY "Director" ''')

In [91]:
df5=pd.DataFrame(cur.fetchall(),columns=[
    'Director',
    'Count',
    'Revenue'
])

In [92]:
df5

                Director  Count  Revenue
0             Aamir Khan      1     1.20
1    Abdellatif Kechiche      1     2.20
2              Adam Leon      1     0.00
3             Adam McKay      4   438.14
4          Adam Shankman      2   157.33
..                   ...    ...      ...
639         Xavier Dolan      2     3.49
640          Yimou Zhang      1    45.13
641     Yorgos Lanthimos      2     8.81
642          Zack Snyder      5   975.74
643        Zackary Adler      1     6.53

[644 rows x 3 columns]

#

In [94]:
cur.execute('''SELECT "Director",COUNT(*) AS movie_count,SUM("Revenue (Millions)")as total_revenue FROM new_data GROUP BY "Director" ORDER BY total_revenue DESC  ''')

In [95]:
df6=pd.DataFrame(cur.fetchall(),columns=[
    'Director',
    'Count',
    'Revenue'
])

In [96]:
df6

              Director  Count  Revenue
0          J.J. Abrams      5  1683.45
1          David Yates      6  1630.51
2    Christopher Nolan      5  1515.09
3          Michael Bay      6  1421.32
4     Francis Lawrence      4  1299.81
..                 ...    ...      ...
639    Alex Ranarivelo      1     0.00
640       Akan Satayev      1     0.00
641      Aisling Walsh      1     0.00
642      Afonso Poyart      1     0.00
643          Adam Leon      1     0.00

[644 rows x 3 columns]

In [99]:
#extra
cur.execute('''SELECT "Director","Revenue (Millions)"  FROM new_data WHERE "Revenue (Millions)" is 0 ''')

In [100]:
cur.fetchall()

[('Sean Foley', 0.0),
 ('Ben Young', 0.0),
 ('Dominique Abel', 0.0),
 ('Patrick Read Johnson', 0.0),
 ('Shawn Burkett', 0.0),
 ('Scott Hicks', 0.0),
 ('Sean Penn', 0.0),
 ('André Øvredal', 0.0),
 ('Terry George', 0.0),
 ('Oriol Paulo', 0.0),
 ('Katie Holmes', 0.0),
 ('Ana Lily Amirpour', 0.0),
 ('Todor Chapkanov', 0.0),
 ('Martin Koolhoven', 0.0),
 ('David Lynch', 0.0),
 ('Fabio Guaglione', 0.0),
 ('Jackson Stewart', 0.0),
 ('Mateo Gil', 0.0),
 ('Gaspar Noé', 0.0),
 ('April Mullen', 0.0),
 ('Akan Satayev', 0.0),
 ('Colm McCarthy', 0.0),
 ('Spike Lee', 0.0),
 ('Liam Gavin', 0.0),
 ('Steven Shainberg', 0.0),
 ('Andy Goddard', 0.0),
 ('Jeffrey G. Hunt', 0.0),
 ('Eric Summer', 0.0),
 ('Quentin Tarantino', 0.0),
 ('Jalil Lespert', 0.0),
 ('David Leveaux', 0.0),
 ('Gary Michael Schultz', 0.0),
 ('Dan Berk', 0.0),
 ('Mike Flanagan', 0.0),
 ('Alexi Pappas', 0.0),
 ('William Oldroyd', 0.0),
 ('Hugo Gélin', 0.0),
 ('Alex Ranarivelo', 0.0),
 ('Mike Flanagan', 0.0),
 ('Gillies MacKinnon', 0.0),
 ('Terry Jones', 0.0),
 ('Rolfe Kanefsky', 0.0),
 ('Paul Verhoeven', 0.0),
 ('Mark Williams', 0.0),
 ('Srdjan Spasojevic', 0.0),
 ('Corey Asraf', 0.0),
 ('Jeff Grace', 0.0),
 ('Michael J. Gallagher', 0.0),
 ('Michael Spierig', 0.0),
 ('Carles Torrens', 0.0),
 ('Amber Tamblyn', 0.0),
 ('Justin Kurzel', 0.0),
 ('Paolo Genovese', 0.0),
 ('Daniel Ragussis', 0.0),
 ('Jaco Van Dormael', 0.0),
 ('Pete Travis', 0.0),
 ('Gregory Jacobs', 0.0),
 ('Glenn Ficarra', 0.0),
 ('Neill Blomkamp', 0.0),
 ('Tony Scott', 0.0),
 ('Alexandros Avranas', 0.0),
 ('Ewan McGregor', 0.0),
 ('Nic Mathieu', 0.0),
 ('Mora Stephens', 0.0),
 ('Ken Loach', 0.0),
 ('Stephen Fingleton', 0.0),
 ('Florian Gallenberger', 0.0),
 ('M. Night Shyamalan', 0.0),
 ('Ken Kwapis', 0.0),
 ('John Butler', 0.0),
 ('Debra Granik', 0.0),
 ('Gary Ross', 0.0),
 ('Will Slocombe', 0.0),
 ('Courtney Hunt', 0.0),
 ('Michael Goi', 0.0),
 ('Frank Coraci', 0.0),
 ('Henry Joost', 0.0),
 ('Jonathan Holbrook', 0.0),
 ('Afonso Poyart', 0.0),
 ('Hope Dickson Leach', 0.0),
 ('Atom Egoyan', 0.0),
 ('John Michael McDonagh', 0.0),
 ('Lasse Hallström', 0.0),
 ('Caleb Vetter', 0.0),
 ('Marcus Dunstan', 0.0),
 ('Simon Aboud', 0.0),
 ('Chris Stokes', 0.0),
 ('Filip Renc', 0.0),
 ('Ed Gass-Donnelly', 0.0),
 ('Jamal Hill', 0.0),
 ('Walter Hill', 0.0),
 ('Tyler Shields', 0.0),
 ('Hisonni Johnson', 0.0),
 ('Adam Leon', 0.0),
 ('Jim Sheridan', 0.0),
 ('Kevin Smith', 0.0),
 ('Mario Van Peebles', 0.0),
 ('John Moore', 0.0),
 ('John R. Leonetti', 0.0),
 ('Saul Dibb', 0.0),
 ('Dito Montiel', 0.0),
 ('Phil Claydon', 0.0),
 ('Matthias Hoene', 0.0),
 ('Gee Malik Linton', 0.0),
 ('Aisling Walsh', 0.0),
 ('Nathan Morlando', 0.0),
 ('Naoko Yamada', 0.0),
 ('Alexandre Aja', 0.0),
 ('Femi Oyeniran', 0.0),
 ('Robert Rodriguez', 0.0),
 ('James Franco', 0.0),
 ('Oz Perkins', 0.0),
 ('Gregory Wilson', 0.0),
 ('Chris McCoy', 0.0),
 ('Ido Fluk', 0.0),
 ('Christopher Smith', 0.0),
 ('Richie Smyth', 0.0),
 ('Greg Kwedar', 0.0),
 ('Christopher Smith', 0.0),
 ('James Lapine', 0.0),
 ('David Lynch', 0.0),
 ('Jérôme Salle', 0.0),
 ('Micheal Bafaro', 0.0),
 ('Gilles Paquet-Brenner', 0.0),
 ('Lisa Addario', 0.0),
 ('Xavier Dolan', 0.0),
 ('Pascal Laugier', 0.0),
 ('Billy Ray', 0.0),
 ('Scot Armstrong', 0.0)]

In [144]:
cur.execute('''SELECT "Title" ,"Year","Revenue (Millions)" ,"Votes","Rating" FROM new_data WHERE "Director" = 'Francis Lawrence' ORDER BY "Rating" DESC''')

In [145]:
df7=pd.DataFrame(cur.fetchall(),columns=[
    'Title',
    'Date',
    'Revenue',
    'Votes',
    'Rating'
])

In [146]:
df7

                                   Title  Date  Revenue   Votes  Rating
0        The Hunger Games: Catching Fire  2013   424.65  525646     7.6
1                            I Am Legend  2007   256.39  565721     7.2
2  The Hunger Games: Mockingjay - Part 1  2014   337.10  331902     6.7
3  The Hunger Games: Mockingjay - Part 2  2015   281.67  202380     6.6

In [143]:
cur.execute("PRAGMA table_info(new_data)")
print(cur.fetchall())

[(0, 'Rank', 'INTEGER', 0, None, 0), (1, 'Title', 'TEXT', 0, None, 0), (2, 'Genre', 'TEXT', 0, None, 0), (3, 'Description', 'TEXT', 0, None, 0), (4, 'Director', 'TEXT', 0, None, 0), (5, 'Actors', 'TEXT', 0, None, 0), (6, 'Year', 'INTEGER', 0, None, 0), (7, 'Runtime (Minutes)', 'INTEGER', 0, None, 0), (8, 'Rating', 'REAL', 0, None, 0), (9, 'Votes', 'INTEGER', 0, None, 0), (10, 'Revenue (Millions)', 'REAL', 0, None, 0), (11, 'Metascore', 'INTEGER', 0, None, 0)]